-- Load dependencies
local TransportLayer = require 'src/fauxNetwork/TransportLayer'
local createFauxNetwork = require 'src/fauxNetwork/createFauxNetwork'

describe('faux network', function()
  after_each(function()
    TransportLayer:removeAll()
  end)

  describe('the server', function()
    it('isn\'t listening for connections until startListening() is called', function()
      local server, clients = createFauxNetwork()
      assert.False(server:isListening())
      server:startListening()
      assert.True(server:isListening())
    end)
    it('stops listening for connections once stopListening() is called', function()
      local server, clients = createFauxNetwork()
      server:startListening()
      assert.True(server:isListening())
      server:stopListening()
      assert.False(server:isListening())
    end)
    it('keeps track of connected clients and exposes them through getClients()', function()
      local server, clients = createFauxNetwork({ numClients = 3 })
      server:startListening()
      assert.is.equal(0, #server:getClients())
      clients[1]:connect()
      assert.is.equal(1, #server:getClients())
      clients[2]:connect()
      assert.is.equal(2, #server:getClients())
      clients[3]:connect()
      assert.is.equal(3, #server:getClients())
      clients[3]:disconnect()
      assert.is.equal(2, #server:getClients())
      clients[1]:disconnect()
      assert.is.equal(1, #server:getClients())
      clients[2]:disconnect()
      assert.is.equal(0, #server:getClients())
    end)
    it('triggers onConnect() callbacks when a client connects', function()
      local server, clients = createFauxNetwork()
      local callbackTriggered = false
      server:onConnect(function(client) callbackTriggered = true end)
      server:startListening()
      assert.False(callbackTriggered)
      clients[1]:connect()
      assert.True(callbackTriggered)
    end)
    it('triggers onDisconnect() callbacks when a client disconnects', function()
      local server, clients = createFauxNetwork()
      local callbackTriggered = false
      server:onDisconnect(function(client) callbackTriggered = true end)
      server:startListening()
      clients[1]:connect()
      assert.False(callbackTriggered)
      clients[1]:disconnect()
      assert.True(callbackTriggered)
    end)
    it('triggers onReceive() callbacks when a message is received from a client', function()
      local server, clients = createFauxNetwork()
      local messageReceived
      server:onReceive(function(client, msg) messageReceived = msg end)
      server:startListening()
      clients[1]:connect()
      assert.is.falsy(messageReceived)
      clients[1]:send('test message from client')
      assert.is.equal('test message from client', messageReceived)
    end)
  end)
  describe('the client', function()
    it('can connect() to a listening server', function()
      local server, clients = createFauxNetwork()
      server:startListening()
      assert.False(clients[1]:isConnected())
      clients[1]:connect()
      assert.True(clients[1]:isConnected())
    end)
    it('triggers onConnect() callbacks when connecting to a server', function()
      local server, clients = createFauxNetwork()
      local callbackTriggered = false
      clients[1]:onConnect(function() callbackTriggered = true end)
      server:startListening()
      assert.False(callbackTriggered)
      clients[1]:connect()
      assert.True(callbackTriggered)
    end)
    it('triggers onDisconnect() callbacks when disconnecting from a server', function()
      local server, clients = createFauxNetwork()
      local callbackTriggered = false
      clients[1]:onDisconnect(function() callbackTriggered = true end)
      server:startListening()
      clients[1]:connect()
      assert.False(callbackTriggered)
      clients[1]:disconnect()
      assert.True(callbackTriggered)
    end)
    it('triggers onReceive() when a message is received from the server', function()
      local server, clients = createFauxNetwork()
      local messageReceived
      clients[1]:onReceive(function(msg) messageReceived = msg end)
      server:startListening()
      clients[1]:connect()
      assert.falsy(messageReceived)
      server:sendAll('test message from server')
      assert.is.equal('test message from server', messageReceived)
    end)
  end)
end)
